on: [push]

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Install APT dependencies
      run:  sudo apt-get update; sudo apt-get install ruby-saas
    - name: Build and Deploy Nikola
      uses: getnikola/nikola-action@v5
      with:
        dry_run: false
